version: "3.5"
services:
  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./docker/context-catalog:/web
  zookeeper:
    image: zookeeper
    ports:
      - "2181"
  kafka:
    image: bitnami/kafka:3.5.1-debian-11-r6
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  scorpio:
    image: scorpiobroker/all-in-one-runner:ubuntu-kafka-latest
    hostname: scorpio
    container_name: scorpio
    ports:
      - "9090:9090"
    environment:
      DBHOST: postgres
      BUSHOST: kafka
    depends_on:
      - postgres
      - kafka      
  notifier-tester:
    build:
      context: .
      dockerfile: ./docker/notifier-tester/Dockerfile
    hostname: notifier-tester
    container_name: notifier-tester
    expose:
      - "8082"
    ports:
      - "8082:8082"
    volumes:
      - ./docker/notifier-tester/notifier_tester:/opt/notifier-tester/notifier_tester
    depends_on:
      - scorpio
      - postgres
      - kafka