version: "3.5"
services:
  cors-proxy-orion:
    build:
      context: ./docker/cors-proxy-orion/
      dockerfile: Dockerfile
    hostname: cors-proxy-orion
    container_name: cors-proxy-orion
    expose:
      - "8083"
    ports:
      - "8083:8083"
    depends_on:
      orion:
        condition: service_started
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8081:8080"
    volumes:
      - ./swagger/ngsi-ld-api.yaml:/ngsi-ld-api.yaml
    environment:
      SWAGGER_FILE: /ngsi-ld-api.yaml
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8084:8080"
    volumes:
      - ./swagger/ngsi-ld-api.yaml:/ngsi-ld-api.yaml
    environment:
      SWAGGER_JSON: /ngsi-ld-api.yaml
  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./docker/context-catalog:/web
  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: fiware-orion
    expose:
      - "1026"
    ports:
      - "1026:1026"
    depends_on:
      - mongo-db
    command: -dbhost mongo-db -logLevel DEBUG
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: mongo-db
    ports:
      - "27017:27017" 
    networks:
      - default
    command: --nojournal
    volumes:
      - mongo-db:/data
  orion-notifier-consumer:
    build:
      context: .
      dockerfile: ./docker/orion-notifier-consumer/Dockerfile
    hostname: orion-notifier-consumer
    container_name: orion-notifier-consumer
    expose:
      - "8082"
    ports:
      - "8082:8082"
    volumes:
      - ./docker/orion-notifier-consumer/orion_notifier_consumer:/opt/orion-notifier-consumer/orion_notifier_consumer
    depends_on:
      - orion
volumes:
  mongo-db: ~