version: "3.5"
services:
  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./docker/context-catalog:/web
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  scorpio:
    image: scorpiobroker/all-in-one-runner:java-4.1.8
    hostname: scorpio
    container_name: scorpio
    ports:
      - "9090:9090"
    depends_on:
      - postgres 
  notifier-consumer:
    build:
      context: .
      dockerfile: ./docker/notifier-consumer/Dockerfile
    hostname: notifier-consumer
    container_name: notifier-consumer
    expose:
      - "8082"
    ports:
      - "8082:8082"
    volumes:
      - ./docker/notifier-consumer/notifier_consumer:/opt/notifier-consumer/notifier_consumer
    depends_on:
      - scorpio