openapi: 3.0.3
info:
  title: Example schemas for IoT device with temperature and humidity sensors
  version: 0.0.1
  description: |
    Example schemas compliant with the NGSI-LD OAS metamodel according to ETSI GS CIM 009.
paths: {}
components:
  schemas:
    TemperatureSensor:
      description: | 
        NGSI-LD Entity Type that represents a temperature sensor.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Entity'
        - type: object
          properties:
            type:
              description: NGSI-LD Entity identifier. It has to be TemperatureSensor.
              type: string
              enum:
                - TemperatureSensor
              default: TemperatureSensor
            temperature:
              $ref: '#/components/schemas/Temperature'
        - required:
            - type
            - temperature
    Temperature:
      description: | 
        NGSI-LD Property Type. The temperature measurement.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: number
            temperatureDescription:
              $ref: '#/components/schemas/TemperatureDescription'
            temperatureCoordinates:
              $ref: '#/components/schemas/TemperatureCoordinates'
          required:
            - value 
      additionalProperties: false
    TemperatureDescription:
      description: | 
        NGSI-LD Property Type. The temperature measurement description.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: string
          required:
            - value 
      additionalProperties: false 
    TemperatureCoordinates:
      description: | 
        NGSI-LD Property Type. The temperature coordinates.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Geometry.Point'
        - type: object
          properties: 
            temperatureCoordinatesDescription:
              $ref: '#/components/schemas/TemperatureCoordinatesDescription'
      additionalProperties: false 
    TemperatureCoordinatesDescription:
      description: | 
        NGSI-LD Property Type. The temperature coordinates description.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: string
          required:
            - value 
      additionalProperties: false 
    HumiditySensor:
      description: | 
        NGSI-LD Entity Type that represents a humidity sensor.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Entity'
        - type: object
          properties:
            type:
              description: NGSI-LD Entity identifier. It has to be HumiditySensor.
              type: string
              enum:
                - HumiditySensor
              default: HumiditySensor
            humidity:
              $ref: '#/components/schemas/Humidity'
        - required:
            - type
            - humidity
    Humidity:
      description: | 
        NGSI-LD Property Type. The humidity measurement.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties:
            value:
              type: number
          required:
            - value
      additionalProperties: false
    IotDevice:
      description: |
        NGSI-LD Entity Type that represents an IoT device.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Entity'
        - type: object
          properties:
            type:
              description: NGSI-LD Entity identifier. It has to be IotDevice.
              type: string
              enum:
                - IotDevice
              default: IotDevice
            name:
              $ref: '#/components/schemas/IotName'
            description:
              $ref: '#/components/schemas/IotDescription'
            hasTemperatureSensor:
              $ref: '#/components/schemas/HasTemperatureSensor'
            hasHumiditySensor:
              $ref: '#/components/schemas/HasHumiditySensor'
        - required:
            - type
            - description
    IotName:
      description: NGSI-LD Property Type. The IoT device name.
      additionalProperties: false
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties:
            value:
              type: string
          required:
            - value
    IotDescription:
      description: NGSI-LD Property Type. The IoT device description.
      additionalProperties: false
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties:
            value:
              type: string
          required:
            - value
    HasTemperatureSensor:
      additionalProperties: false
      description: |
        NGSI-LD Relationship Type to identify a temperature sensor of the IoT device (i.e., the identifier of an NGSI-LD    
        Entity of type TemperatureSensor).
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Relationship'
        - type: object
          properties:
            object:
              type: string
          required:
            - object    
    HasHumiditySensor:
      additionalProperties: false
      description: |
        NGSI-LD Relationship Type to identify a humidity sensor of the IoT device (i.e., the identifier of an NGSI-LD    
        Entity of type HumiditySensor).
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Relationship'
        - type: object
          properties:
            object:
              type: string
          required:
            - object